[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirect for checkout-session endpoint to handle dynamic sessionId
[[redirects]]
  from = "/api/checkout-session/*"
  to = "/.netlify/functions/checkout-session/:splat"
  status = 200